export const authConstants = {
    USER_LOGIN: 'USER_LOGIN',
    USER_LOGOUT: 'USER_LOGOUT',
    USER_SENDEMAIL: 'USER_SENDEMAIL',
    
}
export const problemConstants ={
    USER_PROBLEM : 'USER_PROBLEM',
}

export const userConstants = {
    GET_REALTIME_USERS: 'GET_REALTIME_USERS',
    GET_REALTIME_MESSAGES: 'GET_REALTIME_MESSAGES',
    GET_REAL_TIME_CALLS: 'GET_REAL_TIME_CALLS',    
    GET_REALTIME_PROBLEMS : 'GET_REALTIME-PROBLEMS',
    USER_CALL: 'USER_CALL'
}